// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games/feed": {
            "get": {
                "description": "Get a paginated feed of recommended games for the user or fallback recommendations for anonymous users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get a feed of recommended games",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.FeedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}": {
            "get": {
                "description": "Get details of a game by game ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get details of a game by game ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.GameDetailsResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/comments/create": {
            "post": {
                "description": "Create a new comment for a game or reply to an existing comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Create a new comment or reply",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment Content and Optional Parent ID",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CommentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/comments/get": {
            "post": {
                "description": "Get paginated comments for a specific game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Get comments for a game",
                "parameters": [
                    {
                        "description": "Pagination and Game ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.GetCommentsByGameIdRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/comments/{commentId}": {
            "delete": {
                "description": "Soft delete a comment and all its replies. Only the comment author or game creator can delete.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Delete a comment and its replies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/interactions": {
            "post": {
                "description": "Create an interaction (play, like, bookmark) for a game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create an interaction for a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Interaction details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateInteractionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateInteractionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/seen": {
            "post": {
                "description": "Record a game as seen by the user to improve recommendations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Record a game as seen by the user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.RecordSeenGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/createUser": {
            "post": {
                "description": "Create a new user in the system after Supabase authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UID token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/profile/{userId}": {
            "get": {
                "description": "Get profile for user, following and followers count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.GetUserProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update the profile information for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update User Profile Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.UpdateUserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.UpdateUserProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/bookmarkedGames": {
            "get": {
                "description": "Get paginated list of games bookmarked by a specific user (only accessible by the user themselves)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get bookmarked games of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/followers": {
            "get": {
                "description": "Get paginated list of followers for a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get followers of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/following": {
            "get": {
                "description": "Get paginated list of users followed by a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get users followed by a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/follows": {
            "post": {
                "description": "Create a new follow relationship between the authenticated user and the target user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Follow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to follow",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a follow relationship between the authenticated user and the target user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Unfollow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to unfollow",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/games": {
            "get": {
                "description": "Get paginated list of games created by a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get games created by user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/likedGames": {
            "get": {
                "description": "Get paginated list of games liked by a specific user (only accessible by the user themselves)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get liked games of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}/recentlyPlayedGames": {
            "get": {
                "description": "Get paginated list of games recently played by a specific user (only accessible by the user themselves)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get recently played games of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CommentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.CommentResponse"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateCommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateInteractionRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "playtime": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "play",
                        "like",
                        "bookmark"
                    ]
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateInteractionResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "bio": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "profileImageURL": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.FeedResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "totalGames": {
                    "type": "integer"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.GameDetailsResponse": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.GetCommentsByGameIdRequest": {
            "type": "object",
            "required": [
                "game_id"
            ],
            "properties": {
                "game_id": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginationQuery"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.GetUserProfileResponse": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "followersCount": {
                    "type": "integer"
                },
                "followingCount": {
                    "type": "integer"
                },
                "profileImageURL": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.PaginationQuery": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_size": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.RecordSeenGameResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.SuccessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.UpdateUserProfileRequest": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "profileImageURL": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_api_types.UpdateUserProfileResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Bookmark": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                },
                "gameID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                },
                "gameID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDeleted": {
                    "description": "soft delete baby",
                    "type": "boolean"
                },
                "parent": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Comment"
                },
                "parentID": {
                    "type": "string"
                },
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Comment"
                    }
                },
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Follow": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "follower": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "followerID": {
                    "type": "string"
                },
                "following": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "followingID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Game": {
            "type": "object",
            "properties": {
                "bookmarkCount": {
                    "type": "integer"
                },
                "buttonMapping": {
                    "type": "boolean"
                },
                "commentCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "creatorID": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "embedLink": {
                    "type": "string"
                },
                "gameType": {
                    "type": "string"
                },
                "genre": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Genre"
                },
                "genreID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.UserGameInteraction"
                    }
                },
                "isClaimed": {
                    "type": "boolean"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "isFeatured": {
                    "type": "boolean"
                },
                "isLandscape": {
                    "type": "boolean"
                },
                "likeCount": {
                    "type": "integer"
                },
                "playCount": {
                    "type": "integer"
                },
                "playTime": {
                    "type": "string"
                },
                "seenByUsers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.UserSeenGame"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Tag"
                    }
                },
                "thumbnailFileName": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Like": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                },
                "gameID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.RecentlyPlayed": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                },
                "gameID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastPlayedAt": {
                    "type": "string"
                },
                "playCount": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.Tag": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.User": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "bookmarks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Bookmark"
                    }
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Comment"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "followedBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Follow"
                    }
                },
                "followersCount": {
                    "type": "integer"
                },
                "following": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Follow"
                    }
                },
                "followingCount": {
                    "type": "integer"
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                    }
                },
                "gender": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Like"
                    }
                },
                "profileImageURL": {
                    "type": "string"
                },
                "recentlyPlayed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.RecentlyPlayed"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Tag"
                    }
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.UserGameInteraction": {
            "type": "object",
            "properties": {
                "bookmarkCount": {
                    "type": "integer"
                },
                "commentCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "game": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.Game"
                },
                "gameID": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastInteraction": {
                    "type": "string"
                },
                "likeCount": {
                    "type": "integer"
                },
                "playCount": {
                    "type": "integer"
                },
                "playTime": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_PixelzOrg_PHOLE_git_pkg_models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_PixelzOrg_PHOLE_git_pkg_models.UserSeenGame": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "gameID": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hitbox Backend AKA The P-HOLE",
	Description:      "All you could need",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
